### PR TITLE
Revert commit a430bd960094bdc48559c80da708c849107d4cad

### PR DESCRIPTION
**Pull request by mlocati**
This should fix concrete5 tests

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
@mlocati I think we need to make another release here for this to work with your open PR

**Comment by mlocati** [comment]
Or a new release, or re-create the latest...

**Comment by mlocati** [comment]
This PR is wrong

**Comment by mlocati** [comment]
I'm going to revert this commit

**Pull request merged**
